### ISSUE TITLE
Infinite Scrolling article

### ISSUE THREAD

**Issue by trantrongbinh** [trantrongbinh/FS-Focus#10]
Kéo đến cuối trang tự động load bài viết tiếp theo.

**Comment by damminhtien** [comment]
Bài tiếp theo cần được đánh gái giữa trên độ tương tự ntn? Ban đầu do chủ quan của người đăng bài viết, sau này có thể áp dụng học máy :)

**Comment by trantrongbinh** [comment]
:cry:
