### ISSUE TITLE
Increase views using session

### ISSUE THREAD

**Issue by trantrongbinh** [trantrongbinh/FS-Focus#17]
Tăng lượt xem trong một phiên làm việc.
(Hệ thống cũ là cứ F5 tăng 1 view - chưa hợp lý)

**Comment by trantrongbinh** [comment]
@maivantoan0808

**Comment by trantrongbinh** [comment]
@damminhtien  cái setTimeOut này là cứ auto liên tục à. Nếu vậy thì khi nhiều người truy cập thì sao, việc liên tục như vậy cho nhiều người sẽ ảnh hưởng đến performance hay hoạt động của website ko?

**Comment by damminhtien** [comment]
không, setTimeOut là chỉ lặp lại 1 lần thôi mà, với lại bộ đếm này hoạt động ở trên brower của client, sau khoảng t (s) thì nó gửi ajax lên server để tăng view

**Comment by damminhtien** [comment]
Close issue?

**Comment by maivantoan0808** [comment]
Close gì?
Với thế thì chẳng hạn cứ khoảng 30s thì nó gửi request một lần, vậy cứ 1000 uers thì có thể gửi bao nhiêu request trong 1h.

**Comment by damminhtien** [comment]
hàm setInterval mới là 30s gửi 1 lần, setTimeOut là chỉ sau 30s đầu tiên gửi thôi, thì 1000 user vẫn là 1000 request

**Comment by damminhtien** [comment]
còn dùng session cũng là một ý hay rồi :D
