### ISSUE TITLE
Get related post in page detail article

### ISSUE THREAD

**Issue by trantrongbinh** [trantrongbinh/FS-Focus#38]
Lấy các bài viết liên quan khi xem chi tiết một bài nào đó.
![screenshot from 2018-10-25 08-23-52](https://user-images.githubusercontent.com/27794077/47470287-58391a80-d82f-11e8-84b3-2ec7f0ef8ca6.png)

**Comment by maivantoan0808** [comment]
https://github.com/trantrongbinh/FS-Focus/pull/55

**Comment by maivantoan0808** [comment]
- Related Post lấy theo category_id
- Có chỗ view cái title kia hơi chưa bằng nhau giữa các post chưa biết sửa thế nào
![image](https://user-images.githubusercontent.com/29546280/47845144-cca72700-ddf6-11e8-94b7-82bf2f107596.png)

**Comment by maivantoan0808** [comment]
@damminhtien Hnay đọc cái bài này không biết có áp vào đc ko nhỉ? 
https://viblo.asia/p/xay-dung-he-thong-goi-y-don-gian-cho-website-viblo-YWOZrgLYlQ0

**Comment by damminhtien** [comment]
làm thì ok, nhưng mà phải có server riêng viết bằng python
