### ISSUE TITLE
Resource statistics

### ISSUE THREAD

**Issue by trantrongbinh** [trantrongbinh/FS-Focus#4]
![screenshot from 2018-10-18 23-24-09](https://user-images.githubusercontent.com/27794077/47169151-f52a1e00-d32c-11e8-85de-7e4d76ebc7db.png)

Tạo thống kê theo ngày cho view trên.
(Trước là thống kê tổng tài nguyên)

**Comment by trantrongbinh** [comment]
Assignees: @maivantoan0808

**Comment by maivantoan0808** [comment]
https://github.com/trantrongbinh/FS-Focus/pull/16
